### ISSUE TITLE
DCV tool did not complete DCV for "wa-k20.net"

### ISSUE THREAD

**Issue by chmc3** [UWIT-IAM/cert-service#75]
@jfuega reported that the DCV tool did not successfully complete the validation for wa-k20.net despite it being a domain in the UW DNS that normally would be covered by the old manual process. 
The likely suspect is that this DNS entry appears different from the other standard DNS entries. 
For reference, compare https://barista.cac.washington.edu/dnsmgr/fqdn/wa-k20.net to https://barista.cac.washington.edu/dnsmgr/fqdn/cac.washington.edu.

While this is likely an edge case, I suspect we will encounter similar problems in the future that stem out of the ill-defined requirements for the tool. Hopefully by finding the "edge cases" we will discover and build around that better definition.

**Comment by stea-uw** [comment]
Deleting the in-progress verification in the site UI and allowing the DCV cron to try again seems to have fixed the issue. Assigning to @chmc3 in case you want to verify, otherwise feel free to close this.

**Comment by chmc3** [comment]
Verified, and workaround is getting around this error from Sectigo.

**Comment by stea-uw** [comment]
Yup, that seems right. I can see from the DNS that the correct child records were added: https://barista.cac.washington.edu/dnsmgr/fqdnindex/uwtyeeclub.com.

The Sectigo UI looks a little different from when I saw the issue, but that's probably fine. When I saw the issue, the domain was stuck in "pending validation". This one shows "validated" in the domain details.

FYI, it looks like DCV hasn't run in a few days due to a changed password. I updated the password and it should start working again.
________________________________
